/**
 * Tiny single-page PDF writer used by the mock API to serve realistic invoice
 * previews for seeded documents. ASCII only (Helvetica / WinAnsi).
 */

type Rgb = [number, number, number];

interface PdfText {
  text: string;
  x: number;
  y: number;
  size?: number;
  bold?: boolean;
  color?: Rgb;
}

interface PdfRect {
  x: number;
  y: number;
  width: number;
  height: number;
  fill: Rgb;
}

const INK: Rgb = [0.06, 0.09, 0.16];
const MUTED: Rgb = [0.39, 0.45, 0.55];
const WHITE: Rgb = [1, 1, 1];
const BRAND: Rgb = [0.31, 0.27, 0.9];
const RULE: Rgb = [0.95, 0.96, 0.98];

function escapePdfText(value: string): string {
  return value
    .replace(/₹/g, 'Rs.')
    .replace(/[^\x20-\x7E]/g, '?')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function buildPdf(texts: PdfText[], rects: PdfRect[]): Blob {
  let content = '';
  for (const rect of rects) {
    content += `${rect.fill.join(' ')} rg ${rect.x} ${rect.y} ${rect.width} ${rect.height} re f\n`;
  }
  for (const item of texts) {
    const color = (item.color ?? INK).join(' ');
    content += `BT ${color} rg /${item.bold ? 'F2' : 'F1'} ${item.size ?? 10} Tf ${item.x} ${item.y} Td (${escapePdfText(item.text)}) Tj ET\n`;
  }

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>',
    `<< /Length ${content.length} >>\nstream\n${content}endstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((body, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;
  return new Blob([pdf], { type: 'application/pdf' });
}

export interface InvoicePdfData {
  title: string;
  seller: string;
  invoiceNumber: string | null;
  date: string | null;
  billTo: string;
  itemName: string;
  model: string | null;
  serialNumber: string | null;
  amount: string;
  warranty: string | null;
}

export function createInvoicePdf(data: InvoicePdfData): Blob {
  const texts: PdfText[] = [
    { text: data.seller, x: 48, y: 790, size: 18, bold: true, color: WHITE },
    { text: data.title, x: 48, y: 768, size: 10, color: WHITE },
    { text: 'Invoice No.', x: 48, y: 712, size: 9, color: MUTED },
    { text: data.invoiceNumber ?? '-', x: 48, y: 698, size: 11, bold: true },
    { text: 'Invoice date', x: 230, y: 712, size: 9, color: MUTED },
    { text: data.date ?? '-', x: 230, y: 698, size: 11, bold: true },
    { text: 'Bill to', x: 400, y: 712, size: 9, color: MUTED },
    { text: data.billTo, x: 400, y: 698, size: 11, bold: true },
    { text: 'Description', x: 58, y: 646, size: 9, bold: true, color: MUTED },
    { text: 'Qty', x: 400, y: 646, size: 9, bold: true, color: MUTED },
    { text: 'Amount', x: 470, y: 646, size: 9, bold: true, color: MUTED },
    { text: data.itemName, x: 58, y: 614, size: 11, bold: true },
    { text: '1', x: 404, y: 614, size: 11 },
    { text: data.amount, x: 470, y: 614, size: 11, bold: true },
    { text: `Model: ${data.model ?? 'not stated'}`, x: 58, y: 598, size: 9, color: MUTED },
    { text: `Serial no.: ${data.serialNumber ?? 'not stated'}`, x: 58, y: 584, size: 9, color: MUTED },
    { text: 'Total (incl. GST)', x: 330, y: 540, size: 11, bold: true },
    { text: data.amount, x: 470, y: 540, size: 12, bold: true },
    { text: `Warranty: ${data.warranty ?? 'not stated on this invoice'}`, x: 48, y: 490, size: 10 },
    { text: 'Goods once sold will be serviced as per the manufacturer warranty terms.', x: 48, y: 474, size: 9, color: MUTED },
    { text: 'Demo document generated by the Bill Locker mock API. Fictional data.', x: 48, y: 60, size: 8, color: MUTED },
  ];
  const rects: PdfRect[] = [
    { x: 0, y: 742, width: 595, height: 100, fill: BRAND },
    { x: 48, y: 636, width: 499, height: 24, fill: RULE },
    { x: 48, y: 528, width: 499, height: 1, fill: [0.85, 0.87, 0.9] },
  ];
  return buildPdf(texts, rects);
}
